# -*- coding: utf-8 -*-
"""Projeto de energia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlfiEvm1nF3GP0VBEwAQ5whOmmHhaX2G
"""

from matplotlib import axes
# Importação de bibliotecas e arquivos
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('/content/Plant_1_Generation_Data.csv')

# Limpeza e organização de dados
df.rename(columns={'SOURCE_KEY':'ID do Painel'}, inplace=True)
df.rename(columns={'DC_POWER':'Corrente C'}, inplace=True)
df.rename(columns={'AC_POWER':'Corrente A'}, inplace=True)
df.rename(columns={'DAILY_YIELD':'Energia Gerada'}, inplace=True)
df.rename(columns={'TOTAL_YIELD':'Energia Total'}, inplace=True)
df = df.drop(columns=['PLANT_ID'])

# Conversão de datas e horas
df['DATE_TIME'] = pd.to_datetime(df['DATE_TIME'], format='%d-%m-%Y %H:%M')
df['Data'] = df['DATE_TIME'].dt.date
df['Hora_Num'] = df['DATE_TIME'].dt.hour
df = df.drop(columns=['DATE_TIME'])

### Analise dos dados

# Energia gerada por dia
plt.figure(figsize=(10, 6))
dtd1_data = df.groupby('Data')['Energia Gerada'].sum()
dtd1_data.plot(kind='bar', color='red')
plt.title('Energia Gerada por Dia')

# Energia gerada por hora
plt.figure(figsize=(10, 6))
dtd2_data = df.groupby('Hora_Num')['Energia Gerada'].mean()
dtd2_data.plot(marker='o')
plt.title('Média de geração de energia por hora do dia')
plt.xlabel('Hora do dia')
plt.ylabel('Energia Gerada')
plt.grid(True)

# Painel que mais gerou
plt.figure(figsize=(10, 6))
dtd3_data = df.groupby('ID do Painel')['Energia Gerada'].mean().sort_values(ascending=False)
dtd3_data.plot(kind='bar')
plt.title('Total de Energia Gerada por Painel')
plt.xlabel('ID do Painel')
plt.ylabel('Energia Gerada')

# Criando as KPIs
energia_total = df['Energia Gerada'].sum()
media_diaria = dtd1_data.mean()
max_energia_gerada = dtd1_data.max()

fig, axs = plt.subplots(1, 3, figsize=(15, 3))
fig.patch.set_facecolor('#f0f0f0')

kpis = [
    ('Energia Total', f'{energia_total:,.0f}'),
    ('Média Diária', f'{media_diaria:,.0f}'),
    ('Pico de Geração', f'{max_energia_gerada:,.0f}')
]

for kp, (label, value) in enumerate(kpis):
    axs[kp].text(0.5, 0.7, label, fontsize=14, ha='center', va='center', fontweight='bold', color='#333333')
    axs[kp].text(0.5, 0.3, value, fontsize=20, ha='center', va='center', fontweight='bold', color='#d62728')
    axs[kp].set_xticks([])
    axs[kp].set_yticks([])
    axs[kp].spines['top'].set_visible(False)
    axs[kp].spines['right'].set_visible(False)
    axs[kp].spines['left'].set_visible(False)
    axs[kp].spines['bottom'].set_visible(False)
    axs[kp].set_facecolor('white')

plt.tight_layout()

#Posicionando as tabelas em um Dashboard
fig = plt.figure(figsize=(15,10))
axes1 = fig.add_subplot(2, 2, 1)
axes2 = fig.add_subplot(2, 2, 2)
axes3 = fig.add_subplot(2, 2, 3)

# Plotagem dos dados nos subplots
dtd1_data.plot(kind='bar', color='red', ax=axes1)
axes1.set_title('Energia Gerada por Dia')
axes1.set_xlabel('')
axes1.set_ylabel('Energia Gerada')

dtd2_data.plot(marker='o', ax=axes2)
axes2.set_title('Média de geração de energia por hora do dia')
axes2.set_xlabel('Hora do dia')
axes2.set_ylabel('Energia Gerada')
axes2.grid(True)

dtd3_data.plot(kind='bar', ax=axes3)
axes3.set_title('Total de Energia Gerada por Painel')
axes3.set_xlabel('ID do Painel')
axes3.set_ylabel('Energia Gerada')

# Adicionar KPIs como texto no quarto subplot
axes4 = fig.add_subplot(2, 2, 4)
axes4.set_xticks([])
axes4.set_yticks([])
axes4.spines['top'].set_visible(False)
axes4.spines['right'].set_visible(False)
axes4.spines['left'].set_visible(False)
axes4.spines['bottom'].set_visible(False)
axes4.set_title('KPIs de Geração de Energia')
axes4.set_facecolor('white')
offset_y = 0.8
for label, value in kpis:
    axes4.text(0.05, offset_y, f'{label}: {value}', fontsize=14, va='center', fontweight='bold')
    offset_y -= 0.2


# Título do dashboard
fig.suptitle('Análise de Produção de Energia Elétrica', fontsize=16)
fig.tight_layout(rect=[0, 0.03, 1, 0.95])

plt.show()
